name: Build PDFs for md

on:
  push:
    branches: [ main ]
    paths:
      - '*.md'
      - '.github/workflows/build-pdfs.yml'

permissions:
  contents: write

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install pandoc and wkhtmltopdf (HTML→PDF engine)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Ensure output folder
        run: mkdir -p assets/pdfs

      - name: Convert markdown to PDF
        run: |
          set -e
          shopt -s nullglob
          for f in *.md; do
            base="${f%.md}"
            # 1) md -> standalone HTML
            pandoc "$f" -f markdown-implicit_figures -t html5 -s \
              --embed-resources --standalone \
              --metadata title="${base}" \
              -o "assets/pdfs/${base}.html" \

            # 2) HTML -> PDF
            wkhtmltopdf \
              --enable-local-file-access \
              "assets/pdfs/${base}.html" \
              "assets/pdfs/${base}.pdf"

            rm -f "assets/pdfs/${base}.html"
            echo "Built assets/pdfs/${base}.pdf"
          done

      - name: Commit PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/pdfs/*.pdf
          git commit -m "Build PDFs for updated docs" || echo "No changes"
          git push
