name: Build PDFs for docs/md

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/md/**.md'

permissions:
  contents: write

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install pandoc and wkhtmltopdf (HTML→PDF engine)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Ensure output folder
        run: mkdir -p assets/pdfs

      - name: Convert markdown to PDF
        run: |
          set -e
          for f in docs/md/*.md; do
            base="$(basename "$f" .md)"
            # 1) md -> standalone HTML (you can link your site CSS if you want)
            pandoc "$f" -f markdown -t html5 -s \
              -o "assets/pdfs/${base}.html" \
              --metadata title="${base}"

            # 2) HTML -> PDF (wkhtmltopdf tends to preserve CSS better than direct LaTeX unless you install TeX)
            wkhtmltopdf \
              --enable-local-file-access \
              "assets/pdfs/${base}.html" \
              "assets/pdfs/${base}.pdf"

            rm -f "assets/pdfs/${base}.html"
            echo "Built assets/pdfs/${base}.pdf"
          done

      - name: Commit PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/pdfs/*.pdf
          git commit -m "Build PDFs for updated docs" || echo "No changes"
          git push
